### ISSUE TITLE
Problema na instalação

### ISSUE THREAD

**Issue by Nikakz** [NozakiLabs/nozaki#5]
Recebo esse erro quanto tento executar 
perl nozaki.pl                                                                               127 ⨯
Can't locate Find/Lib.pm in @INC (you may need to install the Find::Lib module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at nozaki.pl line 8.
BEGIN failed--compilation aborted at nozaki.pl line 8.

**Comment by htrgouvea** [comment]
Oi @Nikakz, você precisa instalar as libs antes de usar a Nozaki, pode usar o seguinte comando:

```bash
$ cpan install Find::Lib JSON YAML::Tiny Mojo::UserAgent
```

Me avise se deu certo

**Comment by htrgouvea** [comment]
Oi @Nikakz, deu certo?

**Comment by htrgouvea** [comment]
Oi @Nikakz, funcionou? Caso continuemos sem resposta iremos considerar como resolvido e fechar essa issue.

**Comment by htrgouvea** [comment]
Estou considerando essa issue como resolvida e fechando a mesma, qualquer coisa pode comentar aqui que abrimos ela novamente.
